### ISSUE TITLE
Loading Loop with Dragon Parts Fairies and Stars

### ISSUE THREAD

**Issue by gmanc2** [SGrondin/botwr#1]
When clicking cook with those options enabled the cook spinner just spins and does not output a recipe. 

https://i.gyazo.com/da73aad162e1982597161727e30e43ad.mp4

https://botwcooking.com/#inventory-wEiauomihQGCAoYCjZyyg4SEg4cGhAWIBIICmY8BlAKSjQGIgYGNiQGIAoIBipGBi4sBnoOHlAGOjwGnhwOGAYaFBIGwmasBhKOeg4uRirjAQLwDi5SHgYeRgYyIjoqMgQKKgYeEhYICgQ

**Comment by SGrondin** [comment]
Yup that's a bug! I'll fix it tomorrow or next weekend. Thanks for reporting it.

**Comment by SGrondin** [comment]
@gmanc2  Fixed! This was a 10/10 bug report, with the video and the inventory link.

**Comment by gmanc2** [comment]
> @gmanc2 Fixed! This was a 10/10 bug report, with the video and the inventory link.

Awesome thanks for the fix! Thank you for making this amazing website for Zelda, I wouldn't mind making a fork and helping young out in the future. LMK if that's possible :)

**Comment by SGrondin** [comment]
You're welcome!

> I wouldn't mind making a fork and helping young out in the future

It is possible, but as you can see from the code it's not exactly the easiest thing to work on!
In my mind this is a completed project and other than fixing bugs and maybe adding an option just for red hearts there's nothing left to do. I don't want to clutter the interface or make it overly complicated, but I'm open to ideas.

**Comment by gmanc2** [comment]
Oh jeez, I thought it was in JS I didn't look at the code! Meta..... Where did you learn ML/OCaml and why did you choose it? Just wondering, sorry I'm responding to the issue I didn't have another contact method. 

> You're welcome!
> 
> > I wouldn't mind making a fork and helping young out in the future
> 
> It is possible, but as you can see from the code it's not exactly the easiest thing to work on!
> In my mind this is a completed project and other than fixing bugs and maybe adding an option just for red hearts there's nothing left to do. I don't want to clutter the interface or make it overly complicated, but I'm open to ideas.

**Comment by SGrondin** [comment]
I learned it by myself. It's a lot easier to get started on it now than it was in 2013-2014, but the learning curve is still extreme. After the first month or so it starts to become easier and you're left with an incredibly productive system. I can make real executables (like C, C++, Go, Rust) or compile it to byte code (and byte code translates 1-to-1 to JS).
I often code for hours on end, sometimes for 2-3 days without ever running the code, and the first time I run it, it works perfectly. Refactoring code is quick and easy because the compiler tells you anything you forgot.

When I (used to) write in JS, I'd have to spend 70%+ of my "brain power" just on keeping track of the shapes of things, not just the type of the variables, but also the status of things. Sometimes you have e.g. "person objects" and functions/methods that operate on person objects, but there are invariants that you have to keep in your head. Examples: you can only call method A on person objects once, you can only call method B after calling method A, you can call method C but only when the person object meets X requirement.

Those things are usually kept in your head and they have a huge impact on your productivity. They force you to write lots of tests, and they make you scared to take on large refactors. But in OCaml you can have the compiler keep track of all of it for you. You can then focus on writing good code, and it will tell you if you broke or forgot anything. You don't need many tests, or sometimes any tests at all. Tests are only testing what you thought about, but what the language can do is tell you about ALL the cases, automatically. And because you can safely refactor as you go, the code stays clean without too much effort.
